### ISSUE TITLE
Calling IR events...Error in cigar(align.gr) : could not find function "cigar"

### ISSUE THREAD

**Issue by zhengjiantao** [lbroseus/SIRFindeR#2]
hello, When I call the "computeIRrates" function, I encounter the problem described in the title
The result of my run is as follows
![image](https://user-images.githubusercontent.com/41890364/100451507-7ea69f80-30f2-11eb-81de-be0d2239ef29.png)
I found the location of the error report in "LR_callIR.R" file
![image](https://user-images.githubusercontent.com/41890364/100451660-bf061d80-30f2-11eb-8ff3-88f6308dc382.png)
This looks like a function, but I can't find it in another file. Maybe there was a problem when I installed SIRFindeR?

Looking forward to your reply. Thank you!

**Comment by lbroseus** [comment]
Hello zhengjiantao,

Thank you very much for pointing that out.
You are right, cigar() is a function from the BIoconductor package GenomicAlignments.
The bug should now be fixed, so that you may want to install SIRFindeR again.

Thank you again!

**Comment by zhengjiantao** [comment]
Thank you for your prompt reply. The bug has indeed been fixed. 
However, I have encountered a new problem recently, a memory overflow error "cannot allocate vector of size 3.8 Gb" when code execution to "Calling IR events...". And I can see that the R program is using up about 112GB of memory. 
Have you ever done any work on R memory optimization? Or how much memory does your R code take up (for a 13GB BAM file) ? so I can find the right machine to run this program.

Looking forward to your reply. Thank you!
