### ISSUE TITLE
computeIRrates can't run, infinite memory...

### ISSUE THREAD

**Issue by zhengjiantao** [lbroseus/SIRFindeR#3]
As the title shows, when I perform this function on a BAM file (13GB), the memory usage continues to increase in the "Calling IR events..." step and 1TB of memory is still report memory overflow.

What's wrong with this? Hope to answer, thank you!

**Comment by lbroseus** [comment]
Hello,
Do you work on a cluster or on your own personal computer? 
This may be due to the fact that the whole bam file is imported into the R session, through the function readGappedReads().
Could you try again on a reduced bam file, for example an extract from only one chromosome? 
Thank you!

**Comment by zhengjiantao** [comment]
Yes, I'm running SIRFindeR on the server.
It seem that even though the BAM file is 13GB in size, 1TB of memory should not report an out-of-memory error...
How big was the BAM file when you were testing it, and how much memory did "computeIRrates" take up at the end of the run?
I will try to divide it BAM into functions according to chromosomes~ Thanks so much for response

**Comment by zhengjiantao** [comment]
> Yes, I'm running SIRFindeR on the server.
> It seem that even though the BAM file is 13GB in size, 1TB of memory should not report an out-of-memory error...
> How big was the BAM file when you were testing it, and how much memory did "computeIRrates" take up at the end of the run?
> I will try to divide it BAM into functions according to chromosomes~ Thanks so much for response

It is feasible to divide BAM into small files according to chromosomes, and then run them separately. 
Later, the results of each CHR can be splicing together to get the final result. 
Thanks again to the author~
