### ISSUE TITLE
Can IRFinder run directly on third-generation sequencing data?

### ISSUE THREAD

**Issue by Zhen-Peng-Wu** [lbroseus/SIRFindeR#4]
While reading your article, it seems that IRFinder, KMA and SIRFindeR in Figure E are running on GM12878 of second-generation sequencing data.Since we can calculate the computeIRrates of the third-generation sequencing data, it is more appropriate for the theoretical tool to run directly on the third-generation sequencing data?

**Comment by lbroseus** [comment]
The SIRFindeR package provides separate functionalities to estimate intron retention (IR) levels from both short and long RNA-seq data.

The SIRratio metric which is described in the article is specifically dedicated to second-generation sequencing data. If you want to estimate IR levels from second-generation data please use the R function estimateSIRratio().

On the other hand, the computeIRrates() functions is an additional tool for estimating IR levels, which only applies to third-generation sequencing data.
